### PR TITLE
XVI:4 reporting statistics

### PR DESCRIPTION
**Pull request by ColinMaudry**
I have started writing guidance to produce statistics, but I can't find a phrasing that's clear enough for my taste. I'd rather use a formal query language :smile: 

I use https://colab.research.google.com/drive/1eEf22g9LlpWard8t7FoIAvDMALik7aOC#scrollTo=8P9LhymuV9zI

What do you think?

### CODE REVIEW

**Comment by ColinMaudry** [comment]
I'm stuck on this one:

> the number and total value of all contracts covered by this Agreement awarded by each such entity, broken down by categories of goods and services according to an internationally recognized uniform classification system

As far as I know, there is no way to know how much a single item is worth, and it's consequently not possible to produce per classification (e.g. CPV or UNSPSC) spending statistics.

**Comment by jpmckinney** [comment]
> I'm stuck on this one:
> 
> > the number and total value of all contracts covered by this Agreement awarded by each such entity, broken down by categories of goods and services according to an internationally recognized uniform classification system
> 
> As far as I know, there is no way to know how much a single item is worth, and it's consequently not possible to produce per classification (e.g. CPV or UNSPSC) spending statistics.

> > the number and total value of all contracts covered by this Agreement awarded by each such entity, broken down by categories of goods and services according to an internationally recognized uniform classification system

In the EU and elsewhere, the entire procedure is classified with a high-level CPV (or similar) code, like https://github.com/open-contracting-extensions/ocds_tenderClassification_extension So, if a field like that is available, we can use it.

**Comment by ColinMaudry** [comment]
Since we're not sure how to present guidance for the production of statistics, we'll ask people to contact us if they have such a requirement and update the guidance based on their use case.

**Comment by ColinMaudry** [comment]
I don't understand the [CI errors](https://github.com/open-contracting-extensions/government-procurement-agreement/pull/44/checks?check_run_id=1090567114), extension.json seems fine.

**Pull request merged**
